INSERT INTO province (provinceName, deleted) VALUES ('Almería', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Cádiz', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Córdoba', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Granada', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Huelva', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Jaén', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Málaga', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Sevilla', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Huesca', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Teruel', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Zaragoza', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Oviedo', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Palma de Mallorca', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Santa Cruz de Tenerife', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Las Palmas de Gran Canaria', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Santander', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Albacete', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Ciudad Real', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Cuenca', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Guadalajara', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Toledo', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Ávila', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Burgos', 0);
INSERT INTO province (provinceName, deleted) VALUES ('León', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Salamanca', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Segovia', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Soria', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Valladolid', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Zamora', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Barcelona', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Gerona', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Lérida', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Tarragona', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Alicante', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Castellón de la Plana', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Valencia', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Badajoz', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Cáceres', 0);
INSERT INTO province (provinceName, deleted) VALUES ('La Coruña', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Lugo', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Orense', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Pontevedra', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Madrid', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Murcia', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Pamplona', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Bilbao', 0);
INSERT INTO province (provinceName, deleted) VALUES ('San Sebastián', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Vitoria', 0);
INSERT INTO province (provinceName, deleted) VALUES ('Logroño', 0);